-- Vous pouvez ajouter des données de test ici si nécessaire
-- Par exemple :
-- INSERT INTO categories (name, description) VALUES ('Informatique', 'Questions sur l''informatique');
-- INSERT INTO categories (name, description) VALUES ('Sciences', 'Questions scientifiques');